### ISSUE TITLE
v1.1.0 only obeys 1 of 2 rules

### ISSUE THREAD

**Issue by jrrdnx** [rsanchez/entry_type#32]
For Entry Type settings, I have 2 rules both under the 'Page' channel and 'Template' field.

Rule 1:  For every template _except_ 'faq', hide the FAQ field.
Rule 2:  For every template _except_ 'partners', hide the Partners field.

Now when I add/edit any entry using the 'faq' template, I can see the FAQ field but not the Partners field (correct).  And when I add/edit any entry using the 'partners' template, I can see the Partners field but not the FAQ field (correct).  But for every other Page channel entry using a template that is not 'faq' or 'partners' I can still see the FAQ field.

**Comment by jrrdnx** [comment]
Ok, finally had this pop up again. Couldn't for the life of me remember what settings had caused this. The template names have changed but the basic issue is the same.

Both rules are using the same channel (Page) and the same field (Template).

Rule #1 hides 3 fields for every template *except* an About template.
Rule #2 hides 1 field for every template *except* a Services template.

Both of these rules work correctly when selecting either the About template or the Services template.  But for any other entry in the Page channel that's using a different template, it only takes the 2nd rule into effect (i.e. a Contact entry that's using a custom Contact template hides the 1 field from Rule #2 correctly, but still display the 3 fields from Rule #1).

Hopefully that makes sense, as it's confusing enough to me just to try to explain.  Let me know if you would still prefer a login and where I can provide you with that info.

I'm now on Entry Type v1.1.3 running on EE 2.9.2.

**Comment by rsanchez** [comment]
Sure, send me a login. Or a db dump and git repo. info at robsanchez dot com
