### ISSUE TITLE
Unable to create new channel fields in EE 2.8.1

### ISSUE THREAD

**Issue by AlexaWebhead** [rsanchez/entry_type#34]
I installed Entry Type into my test site using v 2.8.1 of EE, and whenever I go to create a new channel field now, I only get a page with this error `Unable to load the requested language file: language/english/entry_type_lang.php`

The file exists at that path, and I checked file permissions and that's not the issue, so I'm clueless.

Update: this is the error you get if you don't rename the add-on folder, didn't see this instruction on Devot:ee.

**Comment by InigoWD** [comment]
Hi, I have this problem too. I can't see any instructions about renaming the add-on folder on Devotee or anywhere? What are you referring to?

**Comment by rsanchez** [comment]
See the installation instructions here and let me know if you are still having trouble: https://github.com/rsanchez/entry_type#installation

**Comment by InigoWD** [comment]
Sorry, yes, I see the rename instructions there now. Thanks
