### ISSUE TITLE
Entry Type 1.1.2 conflict with Pages module

### ISSUE THREAD

**Issue by sant3001** [rsanchez/entry_type#40]
I first had the version 1.1.1 and everything was fine but then I installed version 1.1.2 and I started having issues with the Pages module. Basically the issue is the following:

When you are editing an entry, if you don't specify the *channel_id* parameter in the URL, the javascript variable *EntryType* doesn't get defined and therefore everything else seems to fails.
Since the Pages module only specifies the *entry_id* in each one of the links, then the module entry type always fails for every page.

Please let me know if you can find and issue for this bug.

Thanks!

**Comment by rsanchez** [comment]
Thanks. Your detailed report was really helpful in tracking down the issue.
