### ISSUE TITLE
Conflict with Low Search

### ISSUE THREAD

**Issue by KeironLowe92** [rsanchez/entry_type#42]
I've opened an issue with Low Search as well [here](https://getsatisfaction.com/low/topics/conflict-between-low-search-and-entry-type).

I'm not sure which plugin is the issue, but Low Search and Entry Type don't seem to work well together. When they are both enabled I get errors on both the Publish/Edit and New Channel Field pages, it seems to be related to jQuery, so I tried enabling the jQuery module but it didn't fix the issue. 

It looks like the control panel is requesting an file at `/index.php?S=fa7404b35bdd825d2331b40db76526fc&D=cp&C=javascript&M=load&package=low_search&file=EntryType` which is returning an error page saying jQuery cannot be found. Which then results in an error in the console saying `Uncaught SyntaxError: Unexpected token >` 

I get another error, which I believe is caused by the first error saying `Uncaught ReferenceError: EntryTypeFieldSettings is not defined`.

Cheers!

**Comment by rsanchez** [comment]
I just tried installing Low Search and could not replicate, unfortunately. If you have any more information it might be helpful.

**Comment by KeironLowe92** [comment]
Low posted a solution to the problem, looks like it was an issue with Low Search. I'll close this now, cheers!
