### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by herculezs** [rsanchez/entry_type#44]
I decided to use you GREAT plugin as chooser for my matrix fields assigned to channels. I have created 21 type and there is selection of 21 matrix fields. All works fine except 6 types. Is there restriction on how many types you can have (15). Can i override it so I can have as many as I want?

![typefield](https://cloud.githubusercontent.com/assets/10149828/10473907/ab39ed26-71fe-11e5-9da9-0ddc86dbb23e.png)

**Comment by rsanchez** [comment]
Probably too many inputs on that form. You'll likely have to adjust your PHP settings: `max_input_vars` or if you have Suhosin installed, `suhosin.post.max_vars`.

**Comment by herculezs** [comment]
Thank you. That's what I figured. All is fine now.

**Comment by herculezs** [comment]
Quick question if you have a minute:

I'm trying to display entries depending on selected option. Using Entry Type + Switchee and select.

Dropdown exist but doesn't show case.


{exp:channel:entries channel="my_channel" limit="1" dynamic="no"}

    <select>

    {ENTRYTYPE all_options="yes"}
        <option selected="{selected}" value="{option}">{label}</option>
    {/ENTRYTYPE}

    </select>


{exp:switchee variable="{ENTRYTYPE:selected}" parse="inward" match="all"}

    {case value="value1"}
     <h3>value 1</h3>
    {/case}

    {case value="value2"}
    <h3>Value2</h3>
    {/case}

    {case value="value3"}
   <h3>Value 3</h3>
    {/case}

{/exp:switchee}

{/exp:channel:entries}

**Comment by rsanchez** [comment]
You don't need the :selected after your var. just the {your_entry_type_field} will print the value to switchee.
